/**
 * ステージデータ（自動生成）
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-stages.ts
 * stages/*.json + scripts/stageMetadata.ts を統合
 */

import type { StageData } from './types'



export const STAGEDATA: StageData[] = [
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                 d  ",
        "                                                               fon 1",
        "                                                  pfp         abbbbb",
        "                                                 gbbbh        klllll",
        "                                peeo             qlllr        klllll",
        "d                              gbbbbh            qlllr      abbullll",
        "nopoop  d             gh    d  qllllr         d  qlllr d    kllmllll",
        "bbbbbbhonopp     pfepgish 1 nooqllllr     ppoonooqlllronop  kllmllll",
        "llllllsbbbbbh   gbbbbillsbbbbbbillllr    gbbbbbbbbbbbbbbbbbbwllmllll",
        "llllltbbbullr   qlllllvbbbwlllllllllr    qllllllllllllllllllrllmllll",
        "lllllklllmllr   qlllllqlllrlllllllllr    qllllllllllllllllllrllmllll"
      ],
      [
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                ee  ",
        "                                                                    ",
        "                                                                    ",
        "                                                             pf     ",
        "                                                                    ",
        " 0                                                                  ",
        "                                                   ppp              ",
        "      j                 j                                           ",
        "                                                                    ",
        " j             d               j   j          j                     "
      ]
    ]
  },
  {
    "name": "チューリップ農園",
    "engName": "Tulip Plantation",
    "bgm": "bgm1",
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                    34              ",
        "                                                   abc              ",
        "                    2ofefef2                       klm           gbb",
        "                   gbbbbbbbbh                     abbbc          qll",
        " 0 pooooop pfefefpgillllllllrpoop  ppoooo  2 d    klllm          qll",
        "bbbbbbbbbbbbbbbbbbilllllllllsbbbbbbbbbbbbbbh nefeoklllm ppoooop2 qll",
        "lllllllltbbbbbullllllllllllllllllllllllllllsbbbbbbbbbbbbbbbbbbbbbill",
        "llllllllklltbbbbbullllllllltbbbbbullllltulllllllllllllllllllllllllll",
        "llllllllkllklllllmlllllllllklllllmlllltbbulllllltbbbbullllllllllllll"
      ],
      [
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "         pooo                                      pooo        oo   ",
        "            poooo           poppj      d            d               ",
        "                                       n         ofen               ",
        "   j                 j                    j                     j   "
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        " 0  f                                                                 ",
        "bbbbbh    d                                                           ",
        "lllllsbhoonop2                          2 2 2 2 2 4 4                 ",
        "lllllllsbbbbbh efe 2222o                      fefefe                  ",
        "lllllllllllllsbbbbbbbbbbbh    pooop         gbbbbbbbbh       fef   abb",
        "llllltbbbbbbullllllllllllr   gbbbbbbhooooogbillllllllroooooogbbbh  kll",
        "lllllkllllllmllllllllllllr   qllllllsbbbbbillllllllllsbbbbbbilllr  kll",
        "lllllkllllllmlltbbbbbulllr   qllllllllllllllllllllllllllllllllllr  kll",
        "lllllkllllllmllklllllmullr   qllllllllllllllllllllllllllllllllllr  kll",
        "lllllkllllllmllklllllmmllr   qllllllllllllllllllllllllllllllllllr  kll"
      ],
      [
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                   ooooo                                              ",
        "      poo oo                                                          ",
        "                                                                      ",
        "                poooo                                                 ",
        "                                                                      ",
        "                                                                      ",
        "   j           j       j           j               j          j       "
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                            gbbh        ",
        "                                            qllr        ",
        "                                            qllr        ",
        "                                            qllr        ",
        "                       3                    qllr        ",
        "                      abc                   qllr        ",
        "                      klm                   qllr        ",
        "                      DbE                   qllr    pooo",
        " 0 e                  klm                   qllr   abbbb",
        "bbbbc      4      4   klm        4  abbbbc4fqllr   kllll",
        "llllm    abbc   abbc  klm  fefeabc  kllltbbbLBBC   kllll",
        "llltbbc  kllm   kllm  DbbbbbbbbbbE  klllkllllm     kllll",
        "lllkllm  kllm   kllm  kllllllllllm  klltbbullm  4  kllll",
        "lllkllm  kllm   kllm  kllllllllllm  kllklltbbbbbbc kllll",
        "lllkllm  kllm   kllm  kllllllllllm  kllkllkllllllm kllll"
      ],
      [
        "                                                        ",
        "                                                        ",
        "                                                        ",
        "                                                        ",
        "                                                        ",
        "                                                        ",
        "                                                        ",
        "                                                        ",
        "                                                        ",
        "                                         fe             ",
        "    oo                  j      f                        ",
        "                                        po              ",
        "                                           oooooo       ",
        "                                                        ",
        "          j                   j       j               j "
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                      gbbbbh      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "op0                     ee   pop      4               qllllr      ",
        "bbbbbc                 gbbh gbbbh    gh    gbh4       ABBBBC      ",
        "lllllm                 qllr qlllrxxxxqrxxxxqlsh4       zzzz     e ",
        "lllllm   efefe    4    qllr3qlllsbbbbisbbbbillsh4              gbb",
        "lllllm  gbbbbbhxxghxxgbillrxqllllllllllllllllllsh feefo    poogill",
        "lllllm  qlllllsbbisbbillllsbilllllllllllllllllllsbbbbbbh  gbbbilll",
        "llllvbbbillllllllllllllllllllllllllllltbbbbbullllllllllr  qlllllll",
        "llllqlllllllllllllllllllllllllllllllllklllllmllllllllllr  qlllllll"
      ],
      [
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                       d                          ",
        "     poo                               noooo                      ",
        "                                                                  ",
        "         j              j                                      j  "
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "        fef4                                         gbbbbbbh     ",
        "       abbbc         fefef                     gbbh  qllllllr     ",
        " 0     klllm        abbbbbc   poooo4           qllr  ABBBBJlr     ",
        "bbbh   klllmd       klllllm  gbbbbbbhx         qllr       qlr  abb",
        "lllr   klllmnop4 4  klllllm  qllllllsbhxpoxpox4qllr       qlr  kll",
        "lllsbh kllltbbbbbc  klllllm  qlltbulllsbbbbbbbbillr    33jqlr  kll",
        "lllllr klllklllllm  klllllm  qllklmlllllllllllllllr   gbbbilr  kll",
        "lllllr klllklllllm  klllllm  qllklmlllllllllllllllr   qlllllr  kll"
      ],
      [
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                 j                                ",
        "                                                                  ",
        "                                                                  ",
        "              j                          j                        "
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        " 0                  ",
        "bbc          *   abb",
        "llm pooooooooooo kll",
        "llm abbbbbbbbbbc kll",
        "llm kllllllllllm kll",
        "llm kllllllllllm kll"
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                     ",
        "                                                                     ",
        "                           2  2                                      ",
        "                           gbbh       xx                             ",
        "                         d qllr      Fgh                             ",
        "                      4  noqllr      Fqr                             ",
        "                      abbbbqllr      FAC          efef4              ",
        "                      kllllqllr   abbbbc         abbbbc d            ",
        "                    4 kllllqllr   kllllm        4kllllm4np           ",
        " 0 oo               abbbbbbqllr   kllllm d   abbbbulltbbbbc          ",
        "bbbbbc  oo4         kllllllqllr   kllllm4nop kllllmllkllllm  4       ",
        "lllllm abbc  po4  4 kllllllqllr   Dbbbbbbbbbbbulllmllkllltbbbbc   gbb",
        "lllllm kllm abbc  gbbbbbbbbillr   klllllllllllmlllmllklllkllllm   qll",
        "lllllm kllm kllm  qlllllllllllr   klllllllllllmlllmllklllkllllm   qll",
        "lllllm kllm kllm  qlllllllllllr   klllllllllllmlllmllklllkllllm   qll"
      ],
      [
        "                                                                     ",
        "                                                                     ",
        "                                                                     ",
        "                                                                     ",
        "                                                                     ",
        "                                                                     ",
        "                                                                     ",
        "                                                                     ",
        "                                                                     ",
        "                                     d                               ",
        "                                    onooo                            ",
        "                   pooooooo                                          ",
        "                                                                     ",
        "                                                                     ",
        "                                                                     "
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                   4                   ",
        "            gbh    d           efefef             4    ",
        "       gbh  qlr    nop 5      gbbbbbbh           gh    ",
        " 0     qlr  qlr   gbbbbbh   5 qllllllr   gh 3    qr fe ",
        "bbbbhxxqlrxxqlrxxxqlllllrpooppqllllllrxxxqrxxxgbbisbbbb",
        "llllsbbilsbbilsbbbilllllsbbbbbillllllsbbbisbbbillllllll",
        "lllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllllllllllllllllllll"
      ],
      [
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "   j                   j                     j         "
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "             ABBBBJl",
        "                  ql",
        "                  ql",
        "                  ql",
        "          d       ql",
        "          noop    ql",
        "  FgbhG  gbbbbbhG ql",
        "  FqlrG  qllllKCG ql",
        "  FqlrG  qllllrz  ql",
        "  FqlrG  ABBJlr   ql",
        "  FqlrG    Fqlr   ql",
        " 4FqlrG    Fqlr   ql",
        " 3FqlrG    Fqlr   ql",
        " gbilsbbh  Fqlr   ql",
        " ABJllllr  Fqlr  xql",
        "   qllllr  Fqlr Fgil",
        "   qllllr   qlr FABB",
        "   qllllr   qlr     ",
        "   ABBBBC   qlr     ",
        "            qlr     ",
        "            qlr     ",
        "            qlr     ",
        "            qlr     ",
        "      gbh   qlr     ",
        "      qlrxxxqlr     ",
        "      qlsbbbilr     ",
        "      qlllllllr     ",
        "      qlllllllr     ",
        "      qlllllllr     ",
        " 0 ffeqlllllllrooeo ",
        "bbbbbbilllllllsbbbbb",
        "llllllllllllllllllll",
        "llllllllllllllllllll",
        "llllllllllllllllllll"
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                              ",
        "               xxxxxxxx                                       ",
        "               gbbbbbbh                                       ",
        "               qlKBBJlr                                       ",
        "        oop 5  qlrzzqlr   pooo         j                      ",
        "      gbbbbbh  qlr 1qlr  gbbbbbh      gbh                     ",
        "      qlllllr  qlsbbilr  qlllllr      qlsh                    ",
        "      ABJlKBC  ABBBBBBC  ABJlllr      qllsh                   ",
        "        qlr                qlllr      qlllsh                  ",
        "        qlr                qlllr      qllllsh                 ",
        " 0fefefeqlr  gh   gh   gh  qlllr      qlllllsh     5     fefo ",
        "bbbbbbbbilr  qr   qr   qr  qlllr      qllllllsh 53eee35 gbbbbb",
        "llllllllllr  qr  2qr   qr  qlllr      qlllllllsbbbbbbbbbilllll",
        "llllllllllrooqroooqr   qr  qlllr      qlllllllllllllllllllllll",
        "llllllllllsbbisbbbir   qr  qlllr      qlllllllllllllllllllllll"
      ]
    ]
  },
  {
    "theme": "plain",
    "bg": [
      " ",
      " ",
      " ",
      " ",
      "H",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "BBBBBBBBBBBBBBBJllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "                    ",
        " 0    np edede      ",
        "bbbbbbbbbbbbbbbbbbbb",
        "llllllllllllllllllll",
        "llllllllllllllllllll",
        "llllllllllllllllllll"
      ]
    ]
  },
  {
    "theme": "forest",
    "bgm": "bgm2",
    "bg": [
      ""
    ],
    "fg": [
      "    NO  NO               NO      NO            "
    ],
    "stages": [
      [
        "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
        "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
        "UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU",
        "UUUVVVVUUUUUVVUUUUUUUUUUUUUUUVVRRRRVVUUURUUUUUUUUV",
        "UUVVVVVVURRVVVVUUUUUVVRUUUUUVVVVNOVVVVRVVVUUUUUUVV",
        "UVVVVVVVVNVV@!VVRRRVVVVVRRRVVVV@NOV@!VNVVVVRRRRVVV",
        "VV@!VV@!VNV@  !VNO@!VVVV@O!VVV@ NO   !N@  !VNO!VV@",
        "@   !@  !N@    !NO  !@!@ O !V@  NO    N    !NO !@ ",
        "         N      NO       O      NO    N     NO    ",
        "         N      NO       O      NO    N     NO    ",
        "         N      NO       O      NO    N     NO    ",
        " 0   ST  N   W  NO  ST  WO XYYZ NO  STN   W NO ST ",
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbc  abbbbbbbbbbbbbbbbbbb",
        "lllllllllllllllllllllllllllm  klllllllllllllllllll",
        "lllllllllllllllllllllllllllm  klllllllllllllllllll"
      ],
      [
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "   QPQP     QP               QP    QP            Q",
        "  Q    PR  Q  P     QP      Q        P Q P      Q ",
        "RQ             P   Q   P   Q              P    Q  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "                                                  ",
        "    d d             d   dd         d  d  d   d    ",
        "oooononooooooo  o ponpoonno    o ponoono n ponoo  ",
        "                                                  ",
        "                                                  ",
        "                                                  "
      ]
    ]
  }
]
