/**
 * ステージデータ（自動生成）
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-stages.ts
 * stages/*.json + scripts/stageMetadata.ts を統合
 */

import type { StageData } from './types'
import { DekaNasake } from '@/engine/entity/DekaNasake'

export const STAGEDATA: StageData[] = [
  {
    "bg": [
      " ",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y",
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                               ded 1",
        "                                                   f          abbbbb",
        "                                                 gbbbh        klllll",
        "                                 de              qlllr      0 klllll",
        "                               gbbbbh            qlllr      abbullll",
        "    de                gh       qllllr            qlllr      kllmllll",
        "bbbbbbh  nop      f  gish 1 nooqllllr      np   nqlllr nop  kllmllll",
        "llllllsbbbbbh   gbbbbillsbbbbbbillllr    gbbbbbbbbbbbbbbbbbbwllmllll",
        "llllltbbbullr   qlllllvbbbwlllllllllr    qllllllllllllllllllrllmllll",
        "lllllklllmllr   qlllllqlllrlllllllllr    qllllllllllllllllllrllmllll"
      ]
    ]
  },
  {
    "name": "チューリップ農園",
    "engName": "Tulip Plantation",
    "bgm": "bgm1",
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                                    ",
        "                                                    34              ",
        "                                                   abc              ",
        "                    2 edede2                       klm           gbb",
        "       np          gbbbbbbbbh                     abbbc          qll",
        " 0   nooop dfdfdf gillllllllr np   nop     2      klllm    nop   qll",
        "bbbbbbbbbbbbbbbbbbilllllllllsbbbbbbbbbbbbbbh  efe klllm   nooop2 qll",
        "lllllllltbbbbbullllllllllllllllllllllllllllsbbbbbbbbbbbbbbbbbbbbbill",
        "llllllllklltbbbbbullllllllltbbbbbullllltulllllllllllllllllllllllllll",
        "llllllllkllklllllmlllllllllklllllmlllltbbulllllltbbbbullllllllllllll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        " 0  f                                                                 ",
        "bbbbbh                                                                ",
        "lllllsbh  nop2                          2 2 2 2 2 4 4                 ",
        "lllllllsbbbbbh efe 2222d                      fefefe                  ",
        "lllllllllllllsbbbbbbbbbbbh      nop         gbbbbbbbbh       ded   abb",
        "llllltbbbbbbullllllllllllr   gbbbbbbh     gbillllllllr noop gbbbh  kll",
        "lllllkllllllmllllllllllllr   qllllllsbbbbbillllllllllsbbbbbbilllr  kll",
        "lllllkllllllmlltbbbbbulllr   qllllllllllllllllllllllllllllllllllr  kll",
        "lllllkllllllmllklllllmullr   qllllllllllllllllllllllllllllllllllr  kll",
        "lllllkllllllmllklllllmmllr   qllllllllllllllllllllllllllllllllllr  kll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                            gbbh        ",
        "                                            qllr        ",
        "                                            qllr        ",
        "                                            qllr        ",
        "                       3                    qllr        ",
        "                      abc                   qllr        ",
        "                      klm                   qllr        ",
        "                      DbE                   qllr      no",
        " 0 e                  klm             nop   qllr   abbbb",
        "bbbbc      4      4   klm        4  abbbbc4fqllr   kllll",
        "llllm d  abbc   abbc  klm  fef abc  kllltbbbLBBC   kllll",
        "llltbbc  kllm   kllm  DbbbbbbbbbbE  klllkllllm     kllll",
        "lllkllm  kllm   kllm  kllllllllllm  klltbbullm  4  kllll",
        "lllkllm  kllm   kllm  kllllllllllm  kllklltbbbbbbc kllll",
        "lllkllm  kllm   kllm  kllllllllllm  kllkllkllllllm kllll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                      gbbbbh      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "                                                      qllllr      ",
        "op0                     ee   nop      4               qllllr      ",
        "bbbbbc                 gbbh gbbbh    gh    gbh4       ABBBBC      ",
        "lllllm                 qllr qlllrxxxxqrxxxxqlsh4       zzzz    de ",
        "lllllm   edede    4    qllr3qlllsbbbbisbbbbillsh4              gbb",
        "lllllm  gbbbbbhxxghxxgbillrxqllllllllllllllllllsh ff          gill",
        "lllllm  qlllllsbbisbbillllsbilllllllllllllllllllsbbbbbbh  gbbbilll",
        "llllvbbbillllllllllllllllllllllllllllllllllllllllllllllr  qlllllll",
        "llllqllllllllllllllllllllllllllllllllllllllllllllllllllr  qlllllll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                         np       ",
        "        ded4                                         gbbbbbbh     ",
        "       abbbc         fdfdf                     gbbh  qllllllr     ",
        " 0     klllm        abbbbbc    np  4           qllr  ABBBBJlr     ",
        "bbbh   klllm        klllllm  gbbbbbbhx         qllr       qlr  abb",
        "lllr   klllmnop4 4  klllllm  qllllllsbhx  x  x4qllr       qlr  kll",
        "lllsbh kllltbbbbbc  klllllm  qlltbulllsbbbbbbbbillr    33 qlr  kll",
        "lllllr klllklllllm  klllllm  qllklmlllllllllllllllr   gbbbilr  kll",
        "lllllr klllklllllm  klllllm  qllklmlllllllllllllllr   qlllllr  kll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "param": {
      "boss": DekaNasake
    },
    "stages": [
      [
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        "                    ",
        " 0                  ",
        "bbc          *   abb",
        "llm              kll",
        "llm abbbbbbbbbbc kll",
        "llm kllllllllllm kll",
        "llm kllllllllllm kll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                                     ",
        "                                                                     ",
        "                           2d 2                                      ",
        "                           gbbh       xx                             ",
        "                           qllr      Fgh                             ",
        "                      4  noqllr      Fqr                             ",
        "                      abbbbqllr      FAC          efef4              ",
        "                      kllllqllr   abbbbc         abbbbc              ",
        "                    4 kllllqllr   kllllm        4kllllm4np           ",
        " 0  d               abbbbbbqllr   kllllm     abbbbulltbbbbc          ",
        "bbbbbc   e4         kllllllqllr   kllllm4nop kllllmllkllllm  4       ",
        "lllllm abbc   f4  4 kllllllqllr   Dbbbbbbbbbbbulllmllkllltbbbbc   gbb",
        "lllllm kllm abbc  gbbbbbbbbillr   klllllllllllmlllmllklllkllllm   qll",
        "lllllm kllm kllm  qlllllllllllr   klllllllllllmlllmllklllkllllm   qll",
        "lllllm kllm kllm  qlllllllllllr   klllllllllllmlllmllklllkllllm   qll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "                                                       ",
        "            dfd                    4                   ",
        "       ede  gbh                dfdfdf             4    ",
        "       gbh  qlr    nop 5      gbbbbbbh           gh    ",
        " 0     qlr  qlr   gbbbbbh     qllllllr   gh 3    qr fe ",
        "bbbbhxxqlrxxqlrxxxqlllllr d 5 qllllllrxxxqrxxxgbbisbbbb",
        "llllsbbilsbbilsbbbilllllsbbbbbillllllsbbbisbbbillllllll",
        "lllllllllllllllllllllllllllllllllllllllllllllllllllllll",
        "lllllllllllllllllllllllllllllllllllllllllllllllllllllll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "             ABBBBJl",
        "                  ql",
        "                  ql",
        "                  ql",
        "                  ql",
        "          noop    ql",
        "  FgbhG  gbbbbbhG ql",
        "  FqlrG  qllllKCG ql",
        "  FqlrG  qllllrz  ql",
        "  FqlrG  ABBJlr   ql",
        "  FqlrG    Fqlr   ql",
        " 4FqlrG    Fqlr   ql",
        " 3FqlrG    Fqlr   ql",
        " gbilsbbh  Fqlr   ql",
        " ABJllllr  Fqlr  xql",
        "   qllllr  Fqlr Fgil",
        "   qllllr   qlr FABB",
        "   qllllr   qlr     ",
        "   ABBBBC   qlr     ",
        "            qlr     ",
        "            qlr     ",
        "            qlr     ",
        "            qlr     ",
        "      gbh   qlr     ",
        "      qlrxxxqlr     ",
        "      qlsbbbilr     ",
        "      qlllllllr     ",
        "      qlllllllr     ",
        "      qlllllllr     ",
        " 0  f qlllllllr ded ",
        "bbbbbbilllllllsbbbbb",
        "llllllllllllllllllll",
        "llllllllllllllllllll",
        "llllllllllllllllllll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                                              ",
        "               xxxxxxxx                                       ",
        "               gbbbbbbh                                       ",
        "               qlKBBJlr                                       ",
        "        nop 5  qlrzzqlr    nop                                ",
        "      gbbbbbh  qlr 1qlr  gbbbbbh      gbh                     ",
        "      qlllllr  qlsbbilr  qlllllr      qlsh                    ",
        "      ABJlKBC  ABBBBBBC  ABJlllr      qllsh                   ",
        "        qlr                qlllr      qlllsh                  ",
        "        qlr                qlllr      qllllsh                 ",
        " 0fdfdf qlr  gh   gh   gh  qlllr      qlllllsh     5      np  ",
        "bbbbbbbbilr  qr   qr   AC  qlllr      qllllllsh 53ede35 gbbbbb",
        "llllllllllr  qr   qr       qlllr      qlllllllsbbbbbbbbbilllll",
        "llllllllllr  qr   qr       qlllr      qlllllllllllllllllllllll",
        "llllllllllr  qr   qr       qlllr      qlllllllllllllllllllllll"
      ]
    ]
  },
  {
    "bg": [
      "y"
    ],
    "fg": [
      ""
    ],
    "param": {
      "boss": DekaNasake
    },
    "stages": [
      [
        "BBBBBBBBBBBBBBBJllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        "               qllll",
        " 0    np edede qllll",
        "bbbbbbbbbbbbbbbillll",
        "llllllllllllllllllll",
        "llllllllllllllllllll",
        "llllllllllllllllllll"
      ]
    ]
  },
  {
    "bg": [
      " "
    ],
    "fg": [
      ""
    ],
    "stages": [
      [
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                        ",
        "                                  gbbbbb",
        "                                  qlllll",
        "                    gbbbbh        ABJlll",
        "  0   gh          gbillllr        zzqlll",
        "bbbbbbirHHHHHHHHgbillllllrHHHHHHHHHHqlll",
        "lllllllsbbbbbbbbillllllllrIIIIIIIIIIqlll",
        "lllllllllllllllllllllllllrIIIIIIIIIIqlll",
        "lllllllllllllllllllllllllrIIIIIIIIIIqlll"
      ]
    ]
  }
]
