/**
 * ステージデータ自動生成スクリプト
 * stages/*.json を読み込み、テーマデフォルトを適用して src/generated/stages.ts を生成
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

// テーマデフォルト（themeDefaults.tsと同じ値を定義）
const THEME_DEFAULTS: Record<string, { bg: string[]; fg: string[] }> = {
  plain: {
    bg: [' ', ' ', ' ', ' ', 'H', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y', 'y'],
    fg: [''],
  },
  forest: {
    bg: [''],
    fg: [''],
  },
}

interface StageInput {
  name?: string
  engName?: string
  bgm?: string
  theme: string
  bg?: string[]
  fg?: string[]
  layers: string[][]
}

interface StageOutput {
  name?: string
  engName?: string
  bgm?: string
  theme: string
  bg: string[]
  fg: string[]
  stages: string[][]
}

const stagesDir = join(process.cwd(), 'stages')
const outputFile = join(process.cwd(), 'src/generated/stages.ts')

console.log('🔄 Generating stages.ts from JSON files...')

// stages/*.json を読み込み
const files = readdirSync(stagesDir)
  .filter((f: string) => f.match(/^stage-\d{2}\.json$/))
  .sort()

if (files.length === 0) {
  console.error('❌ No stage-XX.json files found in stages/ directory')
  process.exit(1)
}

// 各ステージを読み込み、デフォルト値を適用
const stageData: StageOutput[] = files.map((file: string) => {
  const filePath = join(stagesDir, file)
  const content = readFileSync(filePath, 'utf-8')
  const input = JSON.parse(content) as StageInput

  const theme = input.theme || 'plain'
  const defaults = THEME_DEFAULTS[theme] || THEME_DEFAULTS.plain

  // デフォルト値を適用
  const output: StageOutput = {
    theme,
    bg: input.bg ?? defaults.bg,
    fg: input.fg ?? defaults.fg,
    stages: input.layers,
  }

  // オプショナルフィールドを追加
  if (input.name) output.name = input.name
  if (input.engName) output.engName = input.engName
  if (input.bgm) output.bgm = input.bgm

  return output
})

// TypeScriptコードとして出力
const stageDataJSON = JSON.stringify(stageData, null, 2)

const output = `/**
 * ステージデータ（自動生成）
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-stages.ts
 */

import type { StageData } from '@game/types'

export const STAGEDATA: StageData[] = ${stageDataJSON}
`

// ファイルに書き込み
writeFileSync(outputFile, output, 'utf-8')

console.log(`✅ Generated ${files.length} stages -> ${outputFile}`)
