/**
 * ステージデータ自動生成スクリプト
 * stages/*.json と stageMetadata.ts を統合して src/game/stages.ts を生成
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

const stagesDir = join(process.cwd(), 'stages')
const metadataFile = join(process.cwd(), 'scripts/stageMetadata.ts')
const outputFile = join(process.cwd(), 'src/game/stages.ts')

console.log('🔄 Generating stages.ts from JSON files and metadata...')

// stages/*.json を読み込み
const files = readdirSync(stagesDir)
  .filter((f: string) => f.match(/^stage-\d{2}\.json$/))
  .sort()

if (files.length === 0) {
  console.error('❌ No stage-XX.json files found in stages/ directory')
  process.exit(1)
}

// 各ステージのグリッドデータを読み込み（レイヤー配列形式）
const grids: string[][][] = []
files.forEach((file: string) => {
  const json = readFileSync(join(stagesDir, file), 'utf-8')
  const parsed = JSON.parse(json) as string[][]
  grids.push(parsed)
})

// stageMetadata.tsを読み込み
const metadataContent = readFileSync(metadataFile, 'utf-8')

// 1. import文を抽出
const imports: string[] = []
const importRegex = /^import\s+.*$/gm
let match
while ((match = importRegex.exec(metadataContent)) !== null) {
  imports.push(match[0])
}

// 2. STAGE_METADATAを抽出
const metadataMatch = metadataContent.match(
  /export const STAGE_METADATA[^=]*=\s*(\[[^]*?\n\])/
)
if (!metadataMatch) {
  console.error('❌ Could not parse STAGE_METADATA from stageMetadata.ts')
  process.exit(1)
}

// 3. メタデータをJavaScriptとして評価
const metadataArrayStr = metadataMatch[1]
// DekaNasakeなどのクラス参照を一時的に文字列化して評価
const metadataForEval = metadataArrayStr.replace(/:\s*([A-Z]\w+),/g, ': "$1",')
 
const metadata = new Function(`return ${metadataForEval}`)() as Array<{
  name?: string
  engName?: string
  bgm?: string
  bg: string[]
  fg: string[]
  param?: { boss: string }
}>

if (metadata.length !== grids.length) {
  console.error(
    `❌ Mismatch: ${metadata.length} metadata entries vs ${grids.length} stage files`
  )
  process.exit(1)
}

// 4. StageData[]配列を作成（メタデータ + グリッド統合）
const stageData = metadata.map((meta, index) => ({
  ...meta,
  stages: grids[index], // grids[index]は既にstring[][]（レイヤー配列）
}))

// 5. JSON化
const stageDataJSON = JSON.stringify(stageData, null, 2)

// 6. クラス参照を復元（"boss": "ClassName" → "boss": ClassName）
const stageDataCode = stageDataJSON.replace(/"boss":\s*"(\w+)"/g, '"boss": $1')

// 7. TypeScriptコードとして出力
const output = `/**
 * ステージデータ（自動生成）
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-stages.ts
 * stages/*.json + scripts/stageMetadata.ts を統合
 */

import type { StageData } from './types'

${imports.join('\n')}

export const STAGEDATA: StageData[] = ${stageDataCode}
`

// ファイルに書き込み
writeFileSync(outputFile, output, 'utf-8')

console.log(`✅ Generated ${files.length} stages -> ${outputFile}`)
