/**
 * テーマオーバーライドデータ自動生成スクリプト
 * themes/*.json を読み込み src/generated/themes.ts を生成
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

interface ThemeData {
  blocks: Record<string, { frame: number[]; type: string; param?: Record<string, unknown> }>
  entities: Record<string, { entityClass: string }>
}

const themesDir = join(process.cwd(), 'themes')
const outputFile = join(process.cwd(), 'src/generated/themes.ts')

console.log('🔄 Generating themes.ts from JSON files...')

// themes/*.json を読み込み
const files = readdirSync(themesDir)
  .filter((f: string) => f.endsWith('.json'))
  .sort()

if (files.length === 0) {
  console.error('❌ No theme JSON files found in themes/ directory')
  process.exit(1)
}

// 各テーマを読み込み
const blockOverrides: Record<string, Record<string, unknown>> = {}
const entityOverrides: Record<string, Record<string, unknown>> = {}

files.forEach((file: string) => {
  const themeName = file.replace('.json', '')
  const filePath = join(themesDir, file)
  const content = readFileSync(filePath, 'utf-8')
  const data = JSON.parse(content) as ThemeData

  // 空でないオーバーライドのみ追加
  if (Object.keys(data.blocks).length > 0) {
    blockOverrides[themeName] = data.blocks
  }
  if (Object.keys(data.entities).length > 0) {
    entityOverrides[themeName] = data.entities
  }

  console.log(`  ✅ ${file} (blocks: ${Object.keys(data.blocks).length}, entities: ${Object.keys(data.entities).length})`)
})

// ブロックオーバーライドがある場合のみCollisionTypeをimport
const hasBlockOverrides = Object.keys(blockOverrides).length > 0
const collisionTypeImport = hasBlockOverrides ? "import { CollisionType } from '@game/types'\n" : ''

// TypeScriptコードとして出力
const output = `/**
 * テーマオーバーライドデータ（自動生成）
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-themes.ts
 */

${collisionTypeImport}import type { BlockDataMap, EntityDataMap } from '@game/types'

/**
 * テーマ別ブロックオーバーライド
 */
export const THEME_BLOCK_OVERRIDE: Record<string, BlockDataMap> = ${JSON.stringify(blockOverrides, null, 2).replace(/"type":\s*"(\w+)"/g, 'type: CollisionType.$1')}

/**
 * テーマ別エンティティオーバーライド
 */
export const THEME_ENTITY_OVERRIDE: Record<string, EntityDataMap> = ${JSON.stringify(entityOverrides, null, 2)}
`

// ファイルに書き込み
writeFileSync(outputFile, output, 'utf-8')

console.log(`\n✅ Generated themes -> ${outputFile}`)
